### ISSUE TITLE
BUG: Delayed "Back-off" Animation

### ISSUE THREAD

**Issue by aaisara12** [aaisara12/Project-Ronin#64]
**Describe the bug**
Player and enemy "back-off" animation are delayed further and further when being repeatedly attacked. The time between when the attack hits and when the character visually reacts to the hit (with animations) becomes longer and longer.

**To Reproduce**
1. Play the scene 'Main' (or any scene with a player and an enemy character)
2. Allow the enemy to walk up to your character and begin attacking you repeatedly (or walk up to the enemy and spam click attack them)

**Expected behavior**
The character should instantly interrupt its current animation to begin the "back-off" animation when hit by an attack.

**Screenshots**
The attached video shows the last few hits to the player (which are the most delayed)

**Additional context**
I believe it has something to do with the animator not transitioning properly out of the "back-off" state into itself again, but not completely sure.

https://user-images.githubusercontent.com/68300841/160226135-9c5576be-db37-4381-a204-6c83f44a41f5.mp4

**Comment by JohnnyXiangyu** [comment]
I think this has already been fixed last quarter?

**Comment by aaisara12** [comment]
I know you did make a push to address this last quarter, but it seems that the bug has resurfaced :((

Do you think you'd be able to check it out again?

**Comment by JohnnyXiangyu** [comment]
yea I'll check it out

**Comment by aaisara12** [comment]
Great, looks good! 
#78
