### ISSUE TITLE
Attack While Moving State Machine Implementation

### ISSUE THREAD

**Issue by aaisara12** [aaisara12/Project-Ronin#71]
### Description
Modify the `Ronin Controller` state machine so that there is a state for attacking while moving that should be entered when the character receives an attack command while in the movement state. Additional parameters will be needed in the state machine for specifying the direction the user wishes to attack in.

### Modification Details
_From module_ `N/A`

```
```

### Tests

- [ ] Triggering the `attack` state machine parameter while the character is moving should put the character into the `AttackWhileMoving` state for some fixed duration

**Comment by JohnnyXiangyu** [comment]
attacking while moving would require layered animator, where one layer controls lower body movement and another controls upper body

**Comment by aaisara12** [comment]
We're aiming to structure it like Hades, where the character literally transitions to a completely new state when attacking while in a movement state. On second thought, I think we might not even need a separate state. Instead we can just have the character transition to the attack state and have a state behavior script that calls the `AttackRotate` function that @celebilaw is currently working on.

But yeah, we're not trying to separate the movement and the attacking layers

https://user-images.githubusercontent.com/68300841/162031074-e6a4ed1c-9488-4ff5-b42b-a82391328c76.mp4

**Comment by JohnnyXiangyu** [comment]
in Hades the movement is more like sliding, I'm not sure if keeping movement state while attacking will result in a similar effect

**Comment by JohnnyXiangyu** [comment]
plus this is usually done with root motion not in the code

**Comment by JohnnyXiangyu** [comment]
tho what I see can be done is adding a smoothing out effect in movement script, that  when movement script detects speed change it tries to smooth into that speed instead of directly change it, then we'll get a sort of sliding effect. To have the emergency stop effect in the example, however, we'll need to separate layers/have multiple attack animations to handle the footwork.

**Comment by aaisara12** [comment]
Okay I see thanks for the input -- that does seem pretty tough to implement. I'll try to look more into what other options we have.
